spring:
  jpa:
    hibernate:
      format_sql: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:netflix-order
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
eureka:
  client:
    enabled: false