spring:
  jpa:
    hibernate:
      format_sql: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:netflix-user
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  zipkin:
    baseUrl: http://localhost:9411/

eureka:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/